spring:
  data:
    elasticsearch:
      host: localhost:9200
      username: elastic
      password: password # 'ELK ?? ??' ???? ??? .env ? ?? ???? ?
      repositories:
        enabled: true
  application:
    name: elk
server:
  port: 9100
